### PR TITLE
Prefer ftplugin to follow Vim convention[EOM]

### PR DESCRIPTION
**Pull request by ujihisa**

### CODE REVIEW

**Comment by vigoux** [comment]
I guess that was a mistake from my part, but I wanted to have the `:PresStart` command only for `markdown` buffers.

So I guess I am missing a `-buffer` in the autocmd.

**Comment by vigoux** [comment]
Latest master should fix the issue you attempted to fix.

**Comment by ujihisa** [comment]
Yes, -buffer is better! :+1:

In this case it doesn't have to be in plugin since it's only for markdown, so I reused this pull request to move from plugin to ftplugin only to allow markdown explicitly ;)

**Review by vigoux — APPROVED** [review]
Yep that's a better way to do so, I was just being lazy.

**Pull request merged**
